### PR TITLE
2D Kernels

### PR DESCRIPTION
**Pull request by jellis18**
This PR implements 2-D GP kernels which solves some problems mentioned in Issue #93. Previously all gaussian process kernels (or priors, think diagonal phi matrix) were assumed to be 1-d (i.e. diagonal). These new commits don't change the API at all so all of the old GP modeling stuff still works the same, but you can now do something like the following to implement a Squared-Exponential Kernel in the daily averaged basis (averaging over 7 days)
```python
@signal_base.function
def create_quant_matrix(toas, dt=1):

    U, _ = utils.create_quantization_matrix(toas, dt=dt, nmin=1)
    avetoas = np.array([toas[idx.astype(bool)].mean() for idx in U.T])
    return U, avetoas

@signal_base.function
def se_kernel(avetoas, log10_sigma=-7, log10_lam=np.log10(30*86400)):
    tm = np.abs(avetoas[None, :] - avetoas[:, None])

    # add to diagonal to make stable
    d = np.eye(tm.shape[0]) * 10**(2*(log10_sigma-1.5))
    return 10**(2*log10_sigma) * np.exp(-tm**2/2/10**(2*log10_lam)) + d

# define signal
log10_sigma = parameter.Uniform(-10, -5)
log10_lam = parameter.Uniform(np.log10(86400), np.log10(1500*86400))
basis = create_quant_matrix(dt=7*86400)
prior = se_kernel(log10_sigma=log10_sigma, log10_lam=log10_lam)
se = gp_signals.BasisGP(prior, basis, name='se')
```

I have written new tests for this and it all seems to work fine with and without spatial correlations except when using the "cliques" method for spatial correlations. @vallis, can you maybe take a look at this?

One other thing that I changed here is how the PSDs are handled which I think clears up Issue #30. Before the "prior" for PSDs, `powerlaw` for instance, would return something in s^3 but the Kernel is expected to be a variance. We would get around this by multiplying by f[0] (same as 1/Tspan) when we constructed the actual variance but this is not general because it wouldn't work for anything but linear frequency spacing and also I had to use this same formalism for all other Basis type signals which means I was multiplying the variance (ECORR) for instance with ones. 

So the new formalism assumes that the "priorFunction in `BasisGP` actually returns a variance. For all other signals this was already the case but now I have changed the PSD definitions to include the df piece so now when they read in the frequency, f, it computes df by `df=np.diff(np.concatenate(np.array([0]), f))`. This way it is correct for whatever type of frequency spacing we have!

Also, as you can see form the commit tags, I'm having problems with Travis again :(.

### CODE REVIEW

**Comment by jellis18** [comment]
One other thing that we probably want to do is to change the way the Basis functions are defined. As of now all basis functions return the basis matrix and a parameter that may or may not be used in the prior Kernel. For example, the Fourier basis returns the F matrix and the sampling frequencies. The PSD type priors then read in the sampling frequencies here. The Kernel above returns the quantization matrix and the average TOAs, which are then used in the Kernel. However, what if we need more than one variable.

I think we should change the output of Basis functions to be the basis matrix and a dictionary of parameters, so the fourier design matrix would return `return F, {'f': f}` and then the PSD can be called internally like `powerlaw(params=params, **labels)`, where `labels` are the dictionary.

This will require re-writing some of the tests but I think it is worth it, especially once we try to model things in time and radio frequency we are going to need both average TOAs and average frequencies.

**Comment by vallis** [comment]
Thanks, Justin. Comments:

- I will look at the cliques tomorrow, but perhaps in the meantime you can accept the request. Are GPs usable without cliques?
- Regarding PSD integration, if the PSD is evaluated at f_0, f_1, f_2, f_3, then it would be more accurate for f_i to multiply 0.5*(f_{i+1} - f_{i-1}), and for f_0 and f_N to multiply half a step. Or even to use Simpson's rule (see Rutger's and my http://www.arxiv.org/abs/1407.6710). That's not what we do now, but it shouldn't affect limits/Bayes ratios.
- Regarding passing the "labels" to powerlaw functions, I think it works (at least in my PR) to pass positional arguments in "params"---that is, powerlaw(f, t, ...) should be able to take everything from params.

**Comment by jellis18** [comment]
Ok so I have to figure out the travis stuff but there are at least two more things I want to do with this.

1. Add tests to make sure 2-D kernels work with selection
2. Modify so that the inverse method will only do cholesky if the array is 2-D. This is important in `SignalCollection` as right now it forms one phi matrix (if any signals have 2-D) and inverts

**Comment by jellis18** [comment]
>>1. Add tests to make sure 2-D kernels work with selection

I actually already did this!

>>2. Modify so that the inverse method will only do cholesky if the array is 2-D. This is important in SignalCollection as right now it forms one phi matrix (if any signals have 2-D) and inverts

This would speed things but may be too much work for this PR. I think it would require a big re-write of KernelMatrix.

@vallis, what do you think?

**Comment by jellis18** [comment]
OK, I'm going to merge this now, the optimization in point 2 above can be taken care of in a different PR. This PR implements the functionality and is tested so lets do it!

**Pull request merged**
