### PR TITLE
Logger configuration Edits

### PR DESCRIPTION
**Pull request by Hazboun6**
This PR just comments out the call to the logger configuration. 
```
logging.basicConfig(format="%(levelname)s: %(name)s: %(message)s", level=logging.INFO)
```
It has been argued that this is the prerogative of the user to do, and more importantly that this results in duplicate error messages when using software that also uses logging.

I'm a bit unclear on whether we need to do anything else to change the behavior, and if we need to warn users of the change.

### CODE REVIEW

**Comment by Hazboun6** [comment]
I don't know why this drug along so many commits. I literally pulled the master branch just before making the edits. Anyways, you can see in the files changes, that there are just three lines commented out.

**Comment by Hazboun6** [comment]
Okay, just for clarity here. The output historically looks like this when we set the noise parameters:

```
INFO: enterprise.signals.signal_base: Setting J0030+0451_430_ASP_efac to 1.1365193945368486
INFO: enterprise.signals.signal_base: Setting J0030+0451_430_PUPPI_efac to 0.9799469185765327
INFO: enterprise.signals.signal_base: Setting J0030+0451_EFF.EBPP.1360_efac to 1.1131774722050722
INFO: enterprise.signals.signal_base: Setting J0030+0451_EFF.EBPP.1410_efac to 0.7317297647944114
INFO: enterprise.signals.signal_base: Setting J0030+0451_EFF.EBPP.2639_efac to 0.9816169162003063
INFO: enterprise.signals.signal_base: Setting J0030+0451_JBO.DFB.1520_efac to 1.0323718949754754
INFO: enterprise.signals.signal_base: Setting J0030+0451_L-wide_ASP_efac to 1.1237984445609916
INFO: enterprise.signals.signal_base: Setting J0030+0451_L-wide_PUPPI_efac to 1.1395353301435847
....
INFO: enterprise.signals.signal_base: Setting J2322+2057_JBO.DFB.1400_efac to 0.8577091151959042
INFO: enterprise.signals.signal_base: Setting J2322+2057_JBO.DFB.1520_efac to 1.428677565632148
INFO: enterprise.signals.signal_base: Setting J2322+2057_NRT.BON.1400_efac to 1.7167103970794015
INFO: enterprise.signals.signal_base: Setting J2322+2057_NRT.BON.1600_efac to 1.1806656373839755
INFO: enterprise.signals.signal_base: Setting J2322+2057_JBO.DFB.1400_log10_equad to -6.758190630422875
INFO: enterprise.signals.signal_base: Setting J2322+2057_JBO.DFB.1520_log10_equad to -7.029452492639104
INFO: enterprise.signals.signal_base: Setting J2322+2057_NRT.BON.1400_log10_equad to -7.1857386295101495
INFO: enterprise.signals.signal_base: Setting J2322+2057_NRT.BON.1600_log10_equad to -6.736449974170599
```

However it seems like INFO message will no longer appear with out the configuration set, i.e. the default level is WARNING. So for instance the following warning still appears,
```
WARNING: ... No sksparse library. Using scipy instead!
```
but it looks like this:
```
No sksparse library. Using scipy instead!
```
There are plusses and minuses to this change, the main minus being that the user base currently expects a bunch of output when setting WN parameters. Personally, I would rather only see messages when there is a warning, as that's when I should pay attention and often the "WARNING some parameter was not set " message gets lost in all the INFO messages. I would still like to hear from folks though.

**Comment by aarchiba** [comment]
Any user who wants to see INFO messages just has to run `logging.basicConfig(level=logging.INFO)`; this can be plonked into example notebooks or scripts or whatever. The problem is putting it in the library.

**Review by paulthebaker — APPROVED** [review]
I think the new behavior is preferred.  We should make an announcement at a DWG call that the default output has changed and noting how to get it back following @aarchiba's example.

**Pull request merged**
