### PR TITLE
Merge dev and do new release

### LINKED ISSUE #384: Support for newer versions of Python (3.11, 3.12)
Currently, it's not possible to install Enterprise from the `master` branch, or using `pip` or `conda`, on Python 3.11, (although it is possible if you install from the `nanograv:dev` branch), and it's not possible to install on Python 3.12 at all (at least, without first patching the code to remove the version cap in `setup.py`). This can result in a situation where trying to install packages that depend on Enterprise (e.g., `enterprise_extensions` or `pint_pal`) on these newer Python versions results in a very old version of Enterprise (that didn't have a cap on the Python version) being installed, and ultimately in an unsolvable environment.

I ran into this in trying to set up an environment for the next NANOGrav data release, where we'd want something like an `anaconda-env.yaml` file or similar, and are trying to use the most recent Python version we can, so having a tagged release on PyPI / conda-forge that supports these newer Python versions would be ideal. I created an older issue about Python 3.11 support back in October (#350), which is now closed as completed, but the changes have only made it to the `nanograv:dev` branch, and not into a release.

It's possible that Enterprise could support Python 3.12 simply by lifting the version cap in `setup.py`, but I don't know if that will cause other things to break.

### PR DESCRIPTION
**Pull request by vhaasteren**
As described in issue #385, merge dev->master and do a new release

- [x] Merge #370 
- [x] Merge #365 

All other changes postponed for merge into master. Those will get updated on the new dev branch

### CODE REVIEW

**Comment by AaronDJohnson** [comment]
I think we need to merge `main` into `dev` to get the macos tests to work.

**Comment by AaronDJohnson** [comment]
Ah yep. It's the usual suspect:
`Cannot find tempo2 install location.`

**Comment by vhaasteren** [comment]
@AaronDJohnson,

It turns out that enterprise_extensions has some dependencies on the dev branch. Is it an idea to just merge dev as-is to accommodate, and deal with tempo2/pint optional dependencies and feather later? Those can go into the dev branch when ready.

**Comment by AaronDJohnson** [comment]
@vhaasteren I think that's a good idea. Lately, I have been more busy than I thought I would be. So let's go ahead and merge and then work on these extra features.

**Comment by AaronDJohnson** [comment]
The tests weren't working because of libstempo/TEMPO2.... Those issues should be solved now. Maybe the tests will pass on rerunning them?

**Comment by AaronDJohnson** [comment]
Two more issues now: TEMPO2 can't be found on the Mac installs and 3.7 is still required for merging.

**Review by AaronDJohnson — APPROVED** [review]

**Pull request merged**
