### PR TITLE
coverage output in xml

### PR DESCRIPTION
**Pull request by ark0015**
This should output the coverage report in the correct format in addition to using the .coveragerc to exclude testing scripts, etc. from the coverage report.

### CODE REVIEW

**Comment by vallis** [comment]
So codecov is only reporting coverage, which is gathered by pytest. But where are we actually setting coverage requirements?

**Comment by vallis** [comment]
Also look at the "out-of-date" branch warning...

**Comment by ark0015** [comment]
> So codecov is only reporting coverage, which is gathered by pytest. But where are we actually setting coverage requirements?

I think that you can set the coverage to fail if it falls below some minimum (https://pytest-cov.readthedocs.io/en/latest/config.html with `--cov-fail-under=MIN`). Do we want a minimum amount of coverage? Was this what you were thinking?

> Also look at the "out-of-date" branch warning
I'm not sure where you are seeing this?

**Comment by vallis** [comment]
Two things:
* codecov/project fails because coverage decreases... but that may be because previous numbers included the test code itself. So we may need to force-merge this PR.  
* The failure must be because of a default rule that coverage can't decrease... that may be too restrictive. Perhaps we could set a threshold at 85%, which would currently pass, then increase it gradually.

**Comment by vallis** [comment]
Actually it looks like you already set a requirement at 50%?

**Comment by ark0015** [comment]
> Actually it looks like you already set a requirement at 50%?

Yeah, I really thought I had it with that one... I'm not sure why. It might have to do with the default threshold? The target I think is the overall coverage and the threshold is the difference between the last one. I will try again with a larger threshold.

**Comment by vallis** [comment]
Seems to be working now. Interesting that the codecov status was updated as soon the 3.7 CI-Test finished... since all three Pythons are running coverage, I suspect that the first one to finish is the one to report. Not a big problem.

**Pull request merged**
