### PR TITLE
Summary and other utilities

### PR DESCRIPTION
**Pull request by jellis18**
This PR makes a few internal changes to the way that we name signals and also implements a few convenience functions for users. Previously all signals had a `signal_name` attribute that is not used in base `enterprise` although it was used in jump proposals and such. The problem is that this name was not unique (for instance both individual and common red noise has `signal_name = 'red noise'`). Also, it was possible to have multiple signals with the exact same naming which could throw errors since the parameters would be named the same. 

The changes here make `signal_name` unique and built in for each `enterprise` signal. Furthermore, you can add an additional name when initializing the `Signal` class as well so `ef = MeasurementNoise()` would give `signal_name='efac'` but `ef = MeasurementNoise(name='extra')` would give `signal_name = 'efac_extra'`.

These signal names are unique to the class but now I have also made it required that the `signal.name` is unique to each signal. In order to do this we take the pulsar name (now stored in the `Signal` and `SignalCollection` instances) and append the signal name to it so we would have `J1713+0747_efac`.

There is a check in `PTA` that makes sure that each `Signal` has a unique name, otherwise an exception is raised asking the user to re-name the duplicate signal. 

Some convenience methods for this are

* `pta.summary()` which prints out something like this:
```
Signal Name                              Signal Class                   no. Parameters      
==========================================================================================
B1855+09_efac                            MeasurementNoise               4                   
__________________________________________________________________________________________
B1855+09_equad                           EquadNoise                     4                   
__________________________________________________________________________________________
B1855+09_ecorr_sherman-morrison          EcorrKernelNoise               4                   
__________________________________________________________________________________________
B1855+09_linear_timing_model             TimingModel                    0                   
__________________________________________________________________________________________
B1855+09_red_noise                       FourierBasisGP                 2                   
__________________________________________________________________________________________
B1855+09_dmx                             BasisGP                        1                   
__________________________________________________________________________________________
B1855+09_sine_wave                       Deterministic                  2                   
__________________________________________________________________________________________
B1855+09_dmequad                         WhiteNoise                     1                   
__________________________________________________________________________________________
B1855+09_phys_ephem                      PhysicalEphemerisSignal        11                  
__________________________________________________________________________________________
B1855+09_common_fourier                  FourierBasisCommonGP           2                   
__________________________________________________________________________________________
B1937+21_efac                            MeasurementNoise               8                   
__________________________________________________________________________________________
B1937+21_equad                           EquadNoise                     8                   
__________________________________________________________________________________________
B1937+21_ecorr_sherman-morrison          EcorrKernelNoise               8                   
__________________________________________________________________________________________
B1937+21_linear_timing_model             TimingModel                    0                   
__________________________________________________________________________________________
B1937+21_red_noise                       FourierBasisGP                 2                   
__________________________________________________________________________________________
B1937+21_dmx                             BasisGP                        1                   
__________________________________________________________________________________________
B1937+21_sine_wave                       Deterministic                  2                   
__________________________________________________________________________________________
B1937+21_dmequad                         WhiteNoise                     1                   
__________________________________________________________________________________________
B1937+21_phys_ephem                      PhysicalEphemerisSignal        11                  
__________________________________________________________________________________________
B1937+21_common_fourier                  FourierBasisCommonGP           2                   
__________________________________________________________________________________________
==========================================================================================
Common params: 26
Total params: 61
Number of pulsars: 2
```
or `pta.summary(print_params=True)`
```
Signal Name                              Signal Class                   no. Parameters      
==========================================================================================
B1855+09_efac                            MeasurementNoise               4                   


params:
"B1855+09_L-wide_PUPPI_efac":Uniform(0.5,1.5)                                             
"B1855+09_L-wide_ASP_efac":Uniform(0.5,1.5)                                               
"B1855+09_430_ASP_efac":Uniform(0.5,1.5)                                                  
"B1855+09_430_PUPPI_efac":Uniform(0.5,1.5)                                                
__________________________________________________________________________________________
B1855+09_equad                           EquadNoise                     4                   


params:
"B1855+09_L-wide_PUPPI_log10_equad":Uniform(-10,-5)                                       
"B1855+09_430_PUPPI_log10_equad":Uniform(-10,-5)                                          
"B1855+09_L-wide_ASP_log10_equad":Uniform(-10,-5)                                         
"B1855+09_430_ASP_log10_equad":Uniform(-10,-5)                                            
__________________________________________________________________________________________
B1855+09_ecorr_sherman-morrison          EcorrKernelNoise               4                   


params:
"B1855+09_430_ASP_log10_ecorr":Uniform(-10,-5)                                            
"B1855+09_L-wide_ASP_log10_ecorr":Uniform(-10,-5)                                         
"B1855+09_430_PUPPI_log10_ecorr":Uniform(-10,-5)                                          
"B1855+09_L-wide_PUPPI_log10_ecorr":Uniform(-10,-5)                                       
__________________________________________________________________________________________
B1855+09_linear_timing_model             TimingModel                    0                   


params:
__________________________________________________________________________________________
B1855+09_red_noise                       FourierBasisGP                 2                   


params:
"B1855+09_log10_A":Uniform(-20,-11)                                                       
"B1855+09_gamma":Uniform(1.01,7)                                                          
__________________________________________________________________________________________
B1855+09_dmx                             BasisGP                        1                   


params:
"B1855+09_dmx_log10_sigma":Uniform(-10,-4)                                                
__________________________________________________________________________________________
B1855+09_sine_wave                       Deterministic                  2                   


params:
"B1855+09_sine_wave_log10_A":Uniform(-10,-5)                                              
"B1855+09_sine_wave_log10_f":Uniform(-9,-7)                                               
__________________________________________________________________________________________
B1855+09_dmequad                         WhiteNoise                     1                   


params:
"B1855+09_dmequad_log10_dmequad":Uniform(-10,-4)                                          
__________________________________________________________________________________________
B1855+09_phys_ephem                      PhysicalEphemerisSignal        11                  


params:
"d_uranus_mass": Normal(0,5.71923361e-11)                                                 
"d_neptune_mass": Normal(0,7.96103855e-11)                                                
"frame_drift_rate":Uniform(-1e-09,1e-09)                                                  
"d_jupiter_mass": Normal(0,1.5497669e-11)                                                 
"jup_orb_elements":Uniform(-0.05,0.05)[6]                                                 
"d_saturn_mass": Normal(0,8.17306184e-12)                                                 
__________________________________________________________________________________________
B1855+09_common_fourier                  FourierBasisCommonGP           2                   


params:
"log10_A":Uniform(-20,-11)                                                                
"gamma":Uniform(1.01,7)                                                                   
__________________________________________________________________________________________
B1937+21_efac                            MeasurementNoise               8                   


params:
"B1937+21_Rcvr_800_GASP_efac":Uniform(0.5,1.5)                                            
"B1937+21_S-wide_ASP_efac":Uniform(0.5,1.5)                                               
"B1937+21_S-wide_PUPPI_efac":Uniform(0.5,1.5)                                             
"B1937+21_L-wide_ASP_efac":Uniform(0.5,1.5)                                               
"B1937+21_Rcvr1_2_GUPPI_efac":Uniform(0.5,1.5)                                            
"B1937+21_Rcvr_800_GUPPI_efac":Uniform(0.5,1.5)                                           
"B1937+21_Rcvr1_2_GASP_efac":Uniform(0.5,1.5)                                             
"B1937+21_L-wide_PUPPI_efac":Uniform(0.5,1.5)                                             
__________________________________________________________________________________________
B1937+21_equad                           EquadNoise                     8                   


params:
"B1937+21_Rcvr1_2_GASP_log10_equad":Uniform(-10,-5)                                       
"B1937+21_L-wide_PUPPI_log10_equad":Uniform(-10,-5)                                       
"B1937+21_S-wide_PUPPI_log10_equad":Uniform(-10,-5)                                       
"B1937+21_Rcvr1_2_GUPPI_log10_equad":Uniform(-10,-5)                                      
"B1937+21_Rcvr_800_GUPPI_log10_equad":Uniform(-10,-5)                                     
"B1937+21_Rcvr_800_GASP_log10_equad":Uniform(-10,-5)                                      
"B1937+21_S-wide_ASP_log10_equad":Uniform(-10,-5)                                         
"B1937+21_L-wide_ASP_log10_equad":Uniform(-10,-5)                                         
__________________________________________________________________________________________
B1937+21_ecorr_sherman-morrison          EcorrKernelNoise               8                   


params:
"B1937+21_Rcvr_800_GASP_log10_ecorr":Uniform(-10,-5)                                      
"B1937+21_Rcvr1_2_GASP_log10_ecorr":Uniform(-10,-5)                                       
"B1937+21_L-wide_ASP_log10_ecorr":Uniform(-10,-5)                                         
"B1937+21_Rcvr1_2_GUPPI_log10_ecorr":Uniform(-10,-5)                                      
"B1937+21_S-wide_ASP_log10_ecorr":Uniform(-10,-5)                                         
"B1937+21_S-wide_PUPPI_log10_ecorr":Uniform(-10,-5)                                       
"B1937+21_Rcvr_800_GUPPI_log10_ecorr":Uniform(-10,-5)                                     
"B1937+21_L-wide_PUPPI_log10_ecorr":Uniform(-10,-5)                                       
__________________________________________________________________________________________
B1937+21_linear_timing_model             TimingModel                    0                   


params:
__________________________________________________________________________________________
B1937+21_red_noise                       FourierBasisGP                 2                   


params:
"B1937+21_log10_A":Uniform(-20,-11)                                                       
"B1937+21_gamma":Uniform(1.01,7)                                                          
__________________________________________________________________________________________
B1937+21_dmx                             BasisGP                        1                   


params:
"B1937+21_dmx_log10_sigma":Uniform(-10,-4)                                                
__________________________________________________________________________________________
B1937+21_sine_wave                       Deterministic                  2                   


params:
"B1937+21_sine_wave_log10_f":Uniform(-9,-7)                                               
"B1937+21_sine_wave_log10_A":Uniform(-10,-5)                                              
__________________________________________________________________________________________
B1937+21_dmequad                         WhiteNoise                     1                   


params:
"B1937+21_dmequad_log10_dmequad":Uniform(-10,-4)                                          
__________________________________________________________________________________________
B1937+21_phys_ephem                      PhysicalEphemerisSignal        11                  


params:
"d_uranus_mass": Normal(0,5.71923361e-11)                                                 
"d_neptune_mass": Normal(0,7.96103855e-11)                                                
"frame_drift_rate":Uniform(-1e-09,1e-09)                                                  
"d_jupiter_mass": Normal(0,1.5497669e-11)                                                 
"jup_orb_elements":Uniform(-0.05,0.05)[6]                                                 
"d_saturn_mass": Normal(0,8.17306184e-12)                                                 
__________________________________________________________________________________________
B1937+21_common_fourier                  FourierBasisCommonGP           2                   


params:
"log10_A":Uniform(-20,-11)                                                                
"gamma":Uniform(1.01,7)                                                                   
__________________________________________________________________________________________
==========================================================================================
Common params: 26
Total params: 61
Number of pulsars: 2
```

* `pta.pulsars` returns a list of pulsar names in the `PTA` object
* `pta.signals` returns a dictionary with the `signal.name` as key and the `Signal` object as value
* `pta.get_signal(signal_name)` which returns the `Signal` given the `signal_name`

The last one could be redundant but these are good for jump proposals and will be useful for building conditional likelihoods and reconstructing signal realizations.

### CODE REVIEW

**Comment by jellis18** [comment]
OK, there were some backward compatibility issues that I think I've fixed now

**Comment by paulthebaker** [comment]
The summary maybe useful metadata.  It looks like you have everything in there that I would want.  The non-unique naming has bit me when making custom jumps in the past.  If this fixes that, then I'm all for it!

Looks good to me.

**Comment by jellis18** [comment]
There is another thing in this PR. The parameters now have methods for "type" which will be "uniform", "normal", etc (basically a lowercase version of the parameter class name).  They also store the function arguments, so `Uniform` has `_pmin`, `_pmax`, `Normal` has `_mu` and `_sigma`, etc. This will be useful for future transformations

**Comment by vallis** [comment]
Looks good, close it if you can get it to CI.

**Pull request merged**
