### PR TITLE
Enterprise v3

### PR DESCRIPTION
**Pull request by paulthebaker**
This PR will take us to enterprise v3.0.0, officially dropping support for python 2.

### CODE REVIEW

**Comment by paulthebaker** [comment]
addresses issue #197

**Comment by stevertaylor** [comment]
Once you push these, I can go back in and remove all the exception clauses for python 2.

**Comment by paulthebaker** [comment]
I was going to do that as part of this PR.  Are they only in `signals/gp_signals.py`?

**Comment by stevertaylor** [comment]
`test_gp_coefficients`.py` too

**Pull request merged**
