### PR TITLE
Introducing an option to choose a reference frequency for DM normalization

### PR DESCRIPTION
**Pull request by bvgoncharov**
This pull request is related to the following topic: [https://github.com/nanograv/enterprise/issues/164](https://github.com/nanograv/enterprise/issues/164)

### CODE REVIEW

**Comment by paulthebaker** [comment]
We aren't using camelcase for any other of the kwargs (`fmax` not `fMax`).  Can you rename the new parameter `fref` to match this style.

Can you move your comments to the docstring e.g. `:param fref:`

We haven't linked to github issues in comments before, so you should remove that too.  @jellis18, do you agree?

**Comment by bvgoncharov** [comment]
@paulthebaker ok, let's wait for @jellis18 to confirm.
As for the issue link, I just thought it would be nice to have some references to default choices of models and normalisations for Enterprise. Perhaps we could add this information to https://enterprise.readthedocs.io/ ? (with or without a link to the issue page) I would be happy to write a short note about DM and red noise normalisation and models for readthedocs.io.

**Comment by jellis18** [comment]
Yes I would follow @paulthebaker's instructions. The explanation and default choice should be in the doctoring `param: fref` but there shouldn't be a link.

**Comment by paulthebaker** [comment]
The docstrings should be used to create autogenerated docs in the module index.  We should probable link that in the sidebar (in addition to the link at the very bottom of the landing page).

Looking now, I see that in the module index doesn't have any entries for `signals.utils` or `signals.white_signals`.  I'll look into why when I get a chance.

**Comment by bvgoncharov** [comment]
@jellis18 @paulthebaker ok, sounds good. I removed the link and moved a comment to the docstring. The comment is quite general, so I moved it to the top, near the description. But please let me know if you think it's more appropriate near `param: fref`

**Comment by jellis18** [comment]
Looks good except `fref` is in MHz not KHz.

**Comment by bvgoncharov** [comment]
@jellis18 , I fixed this. Sorry, I suspected that everything should be in MHz, but got confused by your post [on the issue page](https://github.com/nanograv/enterprise/issues/164):
`Much easier to gauge "strength" of DM signal as with this normalization it is simply the deviation (in seconds) at 1.4 MHz.`
Is must be 1.4 GHz then.

**Comment by paulthebaker** [comment]
Why isn't this letting me squash and merge?  There seems to be a pending status check, but I can't figure out what it is...

**Comment by bvgoncharov** [comment]
@paulthebaker I am not sure. The messages I see below your comment are: "All checks have passed" and "This pull request can be automatically merged by project collaborators"

**Pull request merged**
