### PR TITLE
Editing utils.py to patch py27 functionality

### PR DESCRIPTION
**Pull request by stevertaylor**

### CODE REVIEW

**Comment by paulthebaker** [comment]
Can you add a `- "2.7"` line to the `python:` section of `.travis.yml`.  This will run the travis tests using both python versions, to ensure our tagged "last working 2.7" version actually works.

**Comment by stevertaylor** [comment]
@paulthebaker, @svigeland : I added "2.7" to `.travis.yml`, but travis seems to be having problems with `getargspec`. Is that a python3 only package?

**Comment by stevertaylor** [comment]
The python3 build goes just fine.

**Comment by stevertaylor** [comment]
Wooohoo! Squash and merge, baby!

**Pull request merged**
