### PR TITLE
Adding the general psd for altpol searches

### PR DESCRIPTION
**Pull request by NimaLaal**

### CODE REVIEW

**Comment by vallis** [comment]
It's a linting problem. Just run "black ." and then add/commit/push the changed files).

**Comment by jellis18** [comment]
I see linting problems a lot in PRs here. Just a friendly reminder the [vscode is amazing and has support for automatic formatting](https://code.visualstudio.com/docs/python/editing).  There is also a pre-commit hook that will run black automatically when running `git commit`. You need to run `make init` to set it up.

**Comment by stevertaylor** [comment]
Just a nudge to @NimaLaal to attempt to have this ready to merge before tomorrow.

**Comment by NimaLaal** [comment]
I decided to add the new changes to enterprise_extensions instead of enterprise. The enterprise_extension changes were successfully merged to the master branch last week. They can be found [here](https://github.com/nanograv/enterprise_extensions/pull/126)

**Pull request closed without merging**
