### PR TITLE
Fixed some errors in point 3 of Get Started in CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by stevertaylor**
When following the guidelines in CONTRIBUTING.rst, I had to add recursive options before the requirements_dev.txt and requirements.txt files. Also, `make test` would not run without first installing `libstempo` in my virtual environment.

### CODE REVIEW

**Comment by jellis18** [comment]
Yep, I just forgot to add that. Did you mean to add the three `.rst` files?

**Comment by jellis18** [comment]
@stevertaylor, can you remove the tracking or the `.rst` files as we have a way to auto-generate the docs now via PR #18. After that we can go ahead and merge.

**Comment by stevertaylor** [comment]
Yes, will do.

On Mar 1, 2017, at 10:33 AM, Justin Ellis <notifications@github.com<mailto:notifications@github.com>> wrote:


@stevertaylor<https://github.com/stevertaylor>, can you remove the tracking or the .rst files as we have a way to auto-generate the docs now via PR #18<https://github.com/nanograv/enterprise/pull/18>. After that we can go ahead and merge.

**Comment by stevertaylor** [comment]
Waiting for checks to pass then I'll merge.

**Pull request merged**
